frontend/src/Entity/Course.php
<?php

namespace App\Entity;

use App\Repository\CourseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CourseRepository::class)]
class Course
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $course_name = null;

    #[ORM\ManyToOne(inversedBy: 'courses')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Teacher $teacher = null;

    #[ORM\ManyToMany(targetEntity: Branch::class, mappedBy: 'courses')]
    private Collection $branches;

    #[ORM\Column(type: Types::INTEGER)]
    private ?int $course_duration = null;

    #[ORM\ManyToMany(targetEntity: Semester::class, inversedBy: 'courses')]
    private Collection $semesters;

    /**
     * @var Collection<int, Session>
     */
    #[ORM\OneToMany(targetEntity: Session::class, mappedBy: 'course')]
    private Collection $sessions;

    /**
     * @var Collection<int, AcademicYear>
     */
    #[ORM\ManyToMany(targetEntity: AcademicYear::class, inversedBy: 'courses')]
    private Collection $academicYears;

    public function __construct()
    {
        $this->branches = new ArrayCollection();
        $this->semesters = new ArrayCollection();
        $this->sessions = new ArrayCollection();
        $this->academicYears = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCourseName(): ?string
    {
        return $this->course_name;
    }

    public function setCourseName(string $course_name): static
    {
        $this->course_name = $course_name;

        return $this;
    }

    public function getTeacher(): ?Teacher
    {
        return $this->teacher;
    }

    public function setTeacher(?Teacher $teacher): static
    {
        $this->teacher = $teacher;

        return $this;
    }

    /**
     * @return Collection<int, Branch>
     */
    public function getBranches(): Collection
    {
        return $this->branches;
    }

    public function addBranch(Branch $branch): static
    {
        if (!$this->branches->contains($branch)) {
            $this->branches->add($branch);
            $branch->addCourse($this);
        }

        return $this;
    }

    public function removeBranch(Branch $branch): static
    {
        if ($this->branches->removeElement($branch)) {
            $branch->removeCourse($this);
        }

        return $this;
    }

    public function getCourseDuration(): int
    {
        return $this->course_duration;
    }

    public function setCourseDuration(int $course_duration): static
    {
        $this->course_duration = $course_duration;

        return $this;
    }

    /**
     * @return Collection<int, Semester>
     */
    public function getSemesters(): Collection
    {
        return $this->semesters;
    }

    public function addSemester(Semester $semester): static
    {
        if (!$this->semesters->contains($semester)) {
            $this->semesters->add($semester);
        }

        return $this;
    }

    public function removeSemester(Semester $semester): static
    {
        $this->semesters->removeElement($semester);

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
            $session->setCourse($this);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getCourse() === $this) {
                $session->setCourse(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, AcademicYear>
     */
    public function getAcademicYears(): Collection
    {
        return $this->academicYears;
    }

    public function addAcademicYear(AcademicYear $academicYear): static
    {
        if (!$this->academicYears->contains($academicYear)) {
            $this->academicYears->add($academicYear);
        }

        return $this;
    }

    public function removeAcademicYear(AcademicYear $academicYear): static
    {
        $this->academicYears->removeElement($academicYear);

        return $this;
    }


}

frontend/src/Form/CourseType.php
<?php

namespace App\Form;

use App\Entity\Branch;
use App\Entity\Course;
use App\Entity\Semester;
use App\Entity\Teacher;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CourseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('course_name')
            ->add("course_duration")
            ->add('teacher', EntityType::class, [
                'class' => Teacher::class,
                'choice_label' => 'getDisplayName',
                'by_reference' => false,
            ])
            ->add('branches', EntityType::class, [
                'class' => Branch::class,
                'choice_label' => 'branch_name',
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,

            ])
            ->add('semesters', EntityType::class, [
                'class' => Semester::class,
                'choice_label' => 'semester_name',
                'multiple' => true,
                'expanded' => true,
                'by_reference' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Course::class,
        ]);
    }
}

frontend/src/Controller/CourseController.php
<?php

namespace App\Controller;

use App\Entity\Branch;
use App\Entity\Course;
use App\Form\CourseType;
use App\Repository\CourseRepository;
use App\Services\BranchService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/course')]
class CourseController extends AbstractController
{
    public function __construct(private BranchService $branchService)
    {
    }

    #[Route('/', name: 'app_course_index', methods: ['GET'])]
    public function index(): Response
    {
        return $this->render('course/index.html.twig', [
            'branches' => $this->branchService->getAllBranches(),
        ]);
    }

    #[Route('/new', name: 'app_course_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $course = new Course();
        $form = $this->createForm(CourseType::class, $course);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($course);
            $entityManager->flush();

            return $this->redirectToRoute('app_course_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('course/new.html.twig', [
            'course' => $course,
            'courseForm' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_course_show', methods: ['GET'])]
    public function show(Course $course): Response
    {
        return $this->render('course/show.html.twig', [
            'course' => $course,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_course_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Course $course, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CourseType::class, $course);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_course_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('course/edit.html.twig', [
            'course' => $course,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_course_delete', methods: ['POST'])]
    public function delete(Request $request, Course $course, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$course->getId(), $request->request->get('_token'))) {
            $entityManager->remove($course);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_course_index', [], Response::HTTP_SEE_OTHER);
    }
}

frontend/templates/course/_delete_form.html.twig
<form method="post" action="{{ path('app_course_delete', {'id': course.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ course.id) }}">
    <button class="btn">Delete</button>
</form>

frontend/templates/course/_form.html.twig
{{ form_start(courseForm) }}
<div class="row">
    <div class="col-9">
        <div class="mb-3">
            {{ form_label(courseForm.course_name, 'Course Name', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(courseForm.course_name, {'attr': {'class': 'form-control', 'placeholder': 'Enter course name', 'id': 'courseNameinput'}}) }}
            {{ form_errors(courseForm.course_name) }}
        </div>
    </div><!--end col-->
    <div class="col-3">
        <div class="mb-3">
            {{ form_label(courseForm.course_duration, 'Course duration', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(courseForm.course_duration, {'attr': {'class': 'form-control', 'id': 'courseDurationinput'}}) }}
            {{ form_errors(courseForm.course_duration) }}
        </div>
    </div><!--end col-->
    <div class="col-6">
        <div class="mb-3">
            {{ form_label(courseForm.teacher, 'Teacher', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(courseForm.teacher, {'attr': {'class': 'form-control', 'id': 'teacherInput'}}) }}
            {{ form_errors(courseForm.teacher) }}
        </div>
    </div><!--end col-->
    <div class="col-3">
        <div class="mb-3">
            {{ form_label(courseForm.semesters, 'Semesters', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(courseForm.semesters, {'attr': {'id': 'branchesInput'}}) }}
            {{ form_errors(courseForm.semesters) }}
        </div>
    </div><!--end col-->
    <div class="col-3">
        <div class="mb-3">
            {{ form_label(courseForm.branches, 'Branches', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(courseForm.branches, {'attr': {'id': 'semestersInput'}}) }}
            {{ form_errors(courseForm.branches) }}
        </div>
    </div><!--end col-->

    <div class="col-lg-12">
        <div class="text-end">
            <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
        </div>
    </div><!--end col-->
</div><!--end row-->
{{ form_end(courseForm) }}

frontend/templates/course/edit.html.twig
<!DOCTYPE html>

<title>Edit Course</title>

{% block body %}
    <h1>Edit Course</h1>

    {{ include('course/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_course_index') }}">back to list</a>

    {{ include('course/_delete_form.html.twig') }}
{% endblock %}

frontend/templates/course/index.html.twig
{{ include('partials/main.html.twig') }}

<head>

    {{ include('partials/title-meta.html.twig', {title: 'Courses'}) }}
    <!-- Sweet Alert css-->
    <link href="{{ asset("assets/libs/sweetalert2/sweetalert2.min.css") }}" rel="stylesheet" type="text/css" />



    {{ include('partials/head-css.html.twig') }}

</head>

<body>

<!-- Begin page -->
<div id="layout-wrapper">

    {{ include('partials/menu.html.twig') }}

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">
                {{ include('partials/page-title.html.twig', {pagetitle: 'Management', title: 'Courses'}) }}
                <div class="row">
                    {% for branch in branches %}

                        <div class="col-4">
                            <div class="card">
                                <div class="card-header d-flex justify-content-between">
                                    <h5 class="card-title mb-0">{{ branch.getBranchName }}</h5>
                                </div>
                                <div class="card-body">
                                    <ul class="list-group">
                                        {% for course in branch.getCourses %}
                                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                                {{ course.getCourseName}} <span class="badge bg-success">{{ course.getCourseDuration|date("h:i") }} h</span>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="d-flex justify-content-start align-items-center">
                    <a href="{{ path("app_course_new") }}" class="btn btn-primary waves-effect waves-light">Add Course</a>
                </div>

            </div>
            <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        {{ include('partials/footer.html.twig') }}
    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->



{{ include('partials/customizer.html.twig') }}

{{ include('partials/vendor-scripts.html.twig') }}

<!-- Sweet Alerts js -->
<script src="{{ asset("assets/libs/sweetalert2/sweetalert2.min.js") }}"></script>

<!-- Sweet alert init js-->
<script src="{{ asset("assets/js/pages/sweetalerts.init.js") }}"></script>
<!-- App js -->
<script src="{{ asset("assets/js/app.js") }}"></script>

</body>

</html>

frontend/templates/course/new.html.twig
{{ include('partials/main.html.twig') }}

<head>

    {{ include('partials/title-meta.html.twig', {title: 'New admin'}) }}

    {{ include('partials/head-css.html.twig') }}

</head>

<body>

<!-- Begin page -->
<div id="layout-wrapper">

    {{ include('partials/menu.html.twig') }}

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class="page-content">
            <div class="container-fluid">

                {{ include('partials/page-title.html.twig', {pagetitle: 'New', title: 'Course'}) }}

                <div class="row">

                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header align-items-center d-flex">
                                <h4>
                                    <h4 class="card-title mb-0 flex-grow-1">New Course</h4>
                                </h4>
                            </div>
                            <div class="card-body">
                                {{ include("course/_form.html.twig") }}
                            </div>
                        </div>
                    </div><!--end col-->
                </div><!--end row-->

            </div>
            <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        {{ include('partials/footer.html.twig') }}
    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->



{{ include('partials/customizer.html.twig') }}

{{ include('partials/vendor-scripts.html.twig') }}

<!-- App js -->
<script src="{{ asset("assets/js/app.js") }}"></script>
</body>

</html>

frontend/templates/course/show.html.twig
<!DOCTYPE html>

<title>Course</title>

{% block body %}
    <h1>Course</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ course.id }}</td>
            </tr>
            <tr>
                <th>Course_name</th>
                <td>{{ course.courseName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_course_index') }}">back to list</a>

    <a href="{{ path('app_course_edit', {'id': course.id}) }}">edit</a>

    {{ include('course/_delete_form.html.twig') }}
{% endblock %}